version: '3.9'

services:

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: rtc_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'

  redis:
    image: redis
    ports:
      - '6379:6379'

  livekit:
    image: livekit/livekit-server
    command: >
      --dev
      --bind 0.0.0.0
    ports:
      - '7880:7880'
      - '7881:7881/udp'